# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.IntegerField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=200)),
                ('college_loc', models.CharField(max_length=200)),
                ('avail_sdate', models.DateTimeField()),
                ('avail_edate', models.DateTimeField()),
                ('college_price', models.IntegerField()),
                ('availability', models.BooleanField()),
            ],
        ),
    ]
