# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='college',
            name='college_price',
        ),
    ]
