# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190330_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='college',
            name='college_price',
            field=models.IntegerField(default=100),
        ),
    ]
